if (False):
    raise Exception("Failed purposefully")
